apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploy.name }}
  labels:
    app: {{ .Values.backend.labels.app }}
  namespace: {{ .Values.backend.deploy.namespace }}
spec:
  replicas: {{ .Values.backend.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.labels.app }}
    spec:
      containers:
        - name: {{ .Values.backend.deploy.containers.name }}
          imagePullPolicy: {{ .Values.backend.deploy.containers.imagePullPolicy }}
          image: {{ .Values.backend.deploy.containers.image }}
          ports:
            - containerPort: {{ .Values.backend.deploy.containers.ports.containerPort }}
              name: {{ .Values.backend.deploy.containers.ports.name }}
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/postgres"
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory }}
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory }}
              cpu: {{ .Values.backend.resources.limits.cpu }}
