apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.frontend.deploy.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.labels.app }}
  ports:
  - name: {{ .Values.frontend.service.ports.name }}
    port: {{ .Values.frontend.service.ports.port }}
    nodePort: {{ .Values.frontend.service.ports.nodePort }}
    targetPort: {{ .Values.frontend.service.ports.targetPort }}
