apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: todo-list.apps.127.0.0.1.nip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: todo-frontend-svc
                port:
                  number: 3000
    - host: todo-api.apps.127.0.0.1.nip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: todo-backend-svc
                port:
                  number: 8000
