apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: todo-list
spec:
  podSelector:
    matchLabels:
      app: todo-backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: postgres
